AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A simple backend with a RESTful API endpoint using Amazon API Gateway.
Resources:
  hello:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.hello
      Runtime: nodejs8.10
      CodeUri: .
      Description: A simple backend with a RESTful API endpoint using Amazon API Gateway.
      MemorySize: 512
      Timeout: 10
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref myHelloTable
      Environment:
        Variables:
          myHelloTable: !Ref myHelloTable
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /hello
            Method: POST
        Api2:
          Type: Api
          Properties:
            Path: /hello/{id}
            Method: ANY
  myHelloTable:
    Type: 'AWS::Serverless::SimpleTable'
